### PR TITLE
fix(genesis): Added json labels to all genesis structs

### LINKED ISSUE #926: Add JSON labels to Genesis structs
Some of the structs are missing them, which causes the golangci-lint `musttag` linter to fail. I think it's a good idea to be explicit on there. Fix the issue and remove the `//nolint:musttag` comments to test.

### PR DESCRIPTION
**Pull request by arepala-uml**
1. Added json tags to all the genesis structs.

Closes #926

### CODE REVIEW

File: ledger/common/genesis.go [hunk 1]
```diff
@@ -21,7 +21,7 @@ import (
 
 // GenesisRat is a wrapper to big.Rat that allows for unmarshaling from a bare float from JSON
 type GenesisRat struct {
-	*big.Rat
+	*big.Rat `json:"string"`
```
Comment (agaffney) [inline ledger/common/genesis.go:24]: This is "wrong" and probably not effective in any meaningful way. This field is an embedded struct, and the `GenesisRat` type has custom `UnmarshalJSON` and `MarshalJSON` functions

Comment (arepala-uml) [reply ledger/common/genesis.go]: I have removed it and tested again. Please review it once

**Review by agaffney — APPROVED** [review]
