### PR TITLE
fix(muxer): Return better error message when the peer closes the connection

### LINKED ISSUE #518: Return better error message when the peer closes the connection
We currently propagate the `EOF` returned by the underlying read call, but we could capture this and return a better error such as `the peer closed the connection` or `the connection was closed unexpectedly`

### PR DESCRIPTION
**Pull request by arepala-uml**
1. Replaced plain io.EOF with descriptive wrapped errors like peer closed the connection while reading header: EOF
in Muxer.readLoop(). 
2. Updated downstream handling in setupConnection() function and muxer error forwarding to preserve
the wrapped errors.

Closes #518

### CODE REVIEW

File: muxer/muxer.go [hunk 1]
```diff
@@ -297,10 +298,11 @@ func (m *Muxer) readLoop() {
 		// We use ReadFull because it guarantees to read the expected number of bytes or
 		// return an error
 		if _, err := io.ReadFull(m.conn, msg.Payload); err != nil {
-			if errors.Is(err, io.ErrClosedPipe) {
-				err = io.EOF
+			if errors.Is(err, io.ErrClosedPipe) || errors.Is(err, io.EOF) {
+				m.sendError(fmt.Errorf("peer closed the connection while reading payload: %w", err))
```
Comment (agaffney) [inline muxer/muxer.go:302]: Let's create a `ConnectionClosedError` (or similar) type that wraps the underlying error. This gives consumers something to match against without them having to know that it wraps an `io.EOF` or similar error

File: muxer/muxer.go [hunk 2]
```diff
@@ -297,10 +298,11 @@ func (m *Muxer) readLoop() {
 		// We use ReadFull because it guarantees to read the expected number of bytes or
 		// return an error
 		if _, err := io.ReadFull(m.conn, msg.Payload); err != nil {
-			if errors.Is(err, io.ErrClosedPipe) {
-				err = io.EOF
```
Comment (agaffney) [inline muxer/muxer.go:301]: We still want to map any other EOF-like errors into `io.EOF` to keep existing code working

File: muxer/muxer.go [hunk 3]
```diff
@@ -284,10 +284,11 @@ func (m *Muxer) readLoop() {
 		}
 		header := SegmentHeader{}
 		if err := binary.Read(m.conn, binary.BigEndian, &header); err != nil {
-			if errors.Is(err, io.ErrClosedPipe) {
-				err = io.EOF
+			if errors.Is(err, io.ErrClosedPipe) || errors.Is(err, io.EOF) {
+				m.sendError(fmt.Errorf("peer closed the connection while reading header: %w", err))
```
Comment (agaffney) [inline muxer/muxer.go:288]: We should use a new `ConnectionClosedError` type here like I mentioned below

File: connection.go [hunk 4]
```diff
@@ -286,8 +286,8 @@ func (c *Connection) setupConnection() error {
 				return
 			}
 			if errors.Is(err, io.EOF) || errors.Is(err, io.ErrUnexpectedEOF) {
```
Comment (agaffney) [inline connection.go:288]: We should change this check to look for the `muxer.ConnectionClosedError` type that we create

**Review by agaffney — CHANGES_REQUESTED** [review]

File: connection.go [hunk 5]
```diff
@@ -286,8 +286,8 @@ func (c *Connection) setupConnection() error {
...
-				// Return a bare io.EOF error if error is EOF/ErrUnexpectedEOF
-				c.errorChan <- io.EOF
+				// Preserve the original wrapped error with friendly message
```
[the remark this answers is not in the document]
Comment (arepala-uml) [reply connection.go]: I have made the changes for this comment message and please review it once

File: muxer/muxer.go (hunk 1 above)
Comment (arepala-uml) [reply muxer/muxer.go]: I have added a new ConnectionClosedError and please review it once

File: muxer/muxer.go (hunk 2 above)
Comment (arepala-uml) [reply muxer/muxer.go:301]: I have made the changes for this and please review it once

File: muxer/muxer.go (hunk 3 above)
Comment (arepala-uml) [reply muxer/muxer.go]: I have used a new ConnectionClosedError and please review it once

File: connection.go (hunk 4 above)
Comment (arepala-uml) [reply connection.go]: I have made the changes to look for ConnectionClosedError and please review it once

**Review by agaffney — APPROVED** [review]
